site_name: Help
site_url: https://github.com/pamlib/iyt/
repo_name: pamlib/iyt
repo_url: https://github.com/pamlib/iyt

theme:
  name: material
  custom_dir: docs/assets/overrides
  logo: assets/Logo_Transparent.png
  favicon: assets/Logo_Transparent.png
  palette:
    scheme: fusion-dark
    primary: black
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github

extra_css:
  - assets/style.css

nav:
  - Home: index.md

markdown_extensions:
  - admonition
  - attr_list
  - meta
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - toc:
      permalink: true
  - pymdownx.highlight:
      guess_lang: false
